name: CI
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ssh_key: ${{ secrets.ssh_key }}
    - name: Setup
      run: npm install
